version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: faizan
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=faizan
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env

volumes:
  data: